# Generated by Django 5.0.7 on 2024-09-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_nome_usuario_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_nome',
        ),
    ]
