# Generated by Django 5.0.7 on 2024-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0006_acompanhamento_sabor'),
        ('produto', '0002_remove_produto_descricao_remove_produto_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='produto',
            name='acompanhamentos',
            field=models.ManyToManyField(blank=True, to='ingrediente.acompanhamento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sabor',
            field=models.ManyToManyField(blank=True, to='ingrediente.sabor'),
        ),
    ]
