# Generated by Django 5.0.7 on 2024-09-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0005_tamanho'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingrediente.tamanho'),
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
