# Generated by Django 5.1.1 on 2024-09-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_itempedido_tamanho_delete_tamanho'),
        ('produto', '0002_remove_produto_descricao_remove_produto_imagem_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_pedido',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='preco_total',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
