# Generated by Django 5.1.1 on 2024-09-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0005_tamanho'),
        ('pedido', '0004_remove_pedido_usuario_pedidoproduto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('ingredientes', models.ManyToManyField(to='ingrediente.ingrediente')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingrediente.tamanho')),
            ],
        ),
    ]
