# Generated by Django 5.0.7 on 2024-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_remove_pedidopersonalizado_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pagamento_na_hora', 'Pagar na Hora')], default='pagamento_na_hora', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pagamento_na_hora', 'Pagar na Hora')], default='pagamento_na_hora', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado')], default='pendente', max_length=20),
        ),
    ]
