# Generated by Django 5.0.7 on 2024-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_pedidopersonalizado_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproduto',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pagamento_na_hora', 'Pagar na Entrega')], default='pagamento_na_hora', max_length=20),
        ),
    ]
