# Generated by Django 5.0.7 on 2024-09-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_alter_pedidoproduto_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopersonalizado',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pagamento_na_hora', 'Pagar na Entrega')], default='pagamento_na_hora', max_length=20),
        ),
    ]
