# Generated by Django 5.0.7 on 2024-09-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_pedidopersonalizado_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopersonalizado',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pagamento_na_entrega', 'Pagar na Entrega')], default='pagamento_na_entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidopersonalizado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pagamento_na_entrega', 'Pagar na Entrega')], default='pagamento_na_entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
    ]
