# Generated by Django 5.0.7 on 2024-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_pedidopersonalizado_usuario_pedidoproduto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
