# Generated by Django 5.0.7 on 2024-09-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0002_ingrediente_delete_acompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('acompanhamento', 'Acompanhamento'), ('calda', 'Calda')], max_length=50),
        ),
    ]
