# Generated by Django 5.0.7 on 2024-09-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0003_alter_ingrediente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('acompanhamento', 'Acompanhamento'), ('sabor', 'Sabor')], max_length=50),
        ),
    ]
