# Generated by Django 5.0.7 on 2024-09-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0004_alter_ingrediente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco_adicional', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
