# Generated by Django 5.0.7 on 2024-09-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0006_acompanhamento_sabor'),
        ('pedido', '0006_remove_pedidopersonalizado_ingredientes_and_more'),
        ('produto', '0003_remove_produto_ingredientes_produto_acompanhamentos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
